/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_topWindow (void)
{
  GtkWidget *topWindow;
  GtkWidget *vbox1;
  GtkWidget *mainMenu;
  GtkWidget *menuitem10;
  GtkWidget *menu10;
  GtkWidget *_______n_1;
  GtkWidget *_______o_1;
  GtkWidget *_______s_1;
  GtkWidget *__________a_1;
  GtkWidget *separatormenuitem1;
  GtkWidget *_______q_1;
  GtkWidget *menuitem11;
  GtkWidget *menu11;
  GtkWidget *_______t_1;
  GtkWidget *_______c_1;
  GtkWidget *_______p_1;
  GtkWidget *_______d_1;
  GtkWidget *menuitem12;
  GtkWidget *menu12;
  GtkWidget *menuitem13;
  GtkWidget *menu13;
  GtkWidget *about1;
  GtkWidget *toolbar2;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *toolitem6;
  GtkWidget *tmp_image;
  GtkWidget *new;
  GtkWidget *toolitem5;
  GtkWidget *close;
  GtkWidget *toolitem3;
  GtkWidget *label3;
  GtkWidget *toolitem4;
  GtkWidget *entry1;
  GtkWidget *hpaned1;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow5;
  GtkWidget *treeview5;
  GtkWidget *label1;
  GtkWidget *scrolledwindow6;
  GtkWidget *treeview6;
  GtkWidget *label2;
  GtkWidget *scrolledwindow7;
  GtkWidget *textview1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  topWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (topWindow), 5);
  gtk_window_set_title (GTK_WINDOW (topWindow), _("lifepad2"));
  gtk_window_set_position (GTK_WINDOW (topWindow), GTK_WIN_POS_CENTER);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (topWindow), vbox1);

  mainMenu = gtk_menu_bar_new ();
  gtk_widget_show (mainMenu);
  gtk_box_pack_start (GTK_BOX (vbox1), mainMenu, FALSE, FALSE, 0);

  menuitem10 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem10);
  gtk_container_add (GTK_CONTAINER (mainMenu), menuitem10);

  menu10 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem10), menu10);

  _______n_1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (_______n_1);
  gtk_container_add (GTK_CONTAINER (menu10), _______n_1);

  _______o_1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (_______o_1);
  gtk_container_add (GTK_CONTAINER (menu10), _______o_1);

  _______s_1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (_______s_1);
  gtk_container_add (GTK_CONTAINER (menu10), _______s_1);

  __________a_1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (__________a_1);
  gtk_container_add (GTK_CONTAINER (menu10), __________a_1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menu10), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  _______q_1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (_______q_1);
  gtk_container_add (GTK_CONTAINER (menu10), _______q_1);

  menuitem11 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (menuitem11);
  gtk_container_add (GTK_CONTAINER (mainMenu), menuitem11);

  menu11 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem11), menu11);

  _______t_1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_show (_______t_1);
  gtk_container_add (GTK_CONTAINER (menu11), _______t_1);

  _______c_1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (_______c_1);
  gtk_container_add (GTK_CONTAINER (menu11), _______c_1);

  _______p_1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_show (_______p_1);
  gtk_container_add (GTK_CONTAINER (menu11), _______p_1);

  _______d_1 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (_______d_1);
  gtk_container_add (GTK_CONTAINER (menu11), _______d_1);

  menuitem12 = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_show (menuitem12);
  gtk_container_add (GTK_CONTAINER (mainMenu), menuitem12);

  menu12 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem12), menu12);

  menuitem13 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem13);
  gtk_container_add (GTK_CONTAINER (mainMenu), menuitem13);

  menu13 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem13), menu13);

  about1 = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menu13), about1);

  toolbar2 = gtk_toolbar_new ();
  gtk_widget_show (toolbar2);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar2, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar2), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar2));

  toolitem6 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem6);
  gtk_container_add (GTK_CONTAINER (toolbar2), toolitem6);

  tmp_image = create_pixmap (topWindow, "new.png");
  gtk_widget_show (tmp_image);
  new = (GtkWidget*) gtk_tool_button_new (tmp_image, "");
  gtk_widget_show (new);
  gtk_container_add (GTK_CONTAINER (toolitem6), new);

  toolitem5 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem5);
  gtk_container_add (GTK_CONTAINER (toolbar2), toolitem5);

  tmp_image = create_pixmap (topWindow, "close.png");
  gtk_widget_show (tmp_image);
  close = (GtkWidget*) gtk_tool_button_new (tmp_image, "");
  gtk_widget_show (close);
  gtk_container_add (GTK_CONTAINER (toolitem5), close);

  toolitem3 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem3);
  gtk_container_add (GTK_CONTAINER (toolbar2), toolitem3);

  label3 = gtk_label_new (_("Serach:"));
  gtk_widget_show (label3);
  gtk_container_add (GTK_CONTAINER (toolitem3), label3);

  toolitem4 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem4);
  gtk_container_add (GTK_CONTAINER (toolbar2), toolitem4);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_container_add (GTK_CONTAINER (toolitem4), entry1);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 9679);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (vbox1), hpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (hpaned1), 0);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_paned_pack1 (GTK_PANED (hpaned1), notebook1, FALSE, TRUE);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow5);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_SHADOW_IN);

  treeview5 = gtk_tree_view_new ();
  gtk_widget_show (treeview5);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), treeview5);

  label1 = gtk_label_new (_("\346\214\211\346\227\245\346\234\237"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow6);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow6);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow6), GTK_SHADOW_IN);

  treeview6 = gtk_tree_view_new ();
  gtk_widget_show (treeview6);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), treeview6);

  label2 = gtk_label_new (_("\346\214\211\347\261\273\345\210\253"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);

  scrolledwindow7 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow7);
  gtk_paned_pack2 (GTK_PANED (hpaned1), scrolledwindow7, TRUE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow7), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow7), textview1);

  g_signal_connect ((gpointer) _______n_1, "activate",
                    G_CALLBACK (on________n_1_activate),
                    NULL);
  g_signal_connect ((gpointer) _______o_1, "activate",
                    G_CALLBACK (on________o_1_activate),
                    NULL);
  g_signal_connect ((gpointer) _______s_1, "activate",
                    G_CALLBACK (on________s_1_activate),
                    NULL);
  g_signal_connect ((gpointer) __________a_1, "activate",
                    G_CALLBACK (on___________a_1_activate),
                    NULL);
  g_signal_connect ((gpointer) _______q_1, "activate",
                    G_CALLBACK (on________q_1_activate),
                    NULL);
  g_signal_connect ((gpointer) _______t_1, "activate",
                    G_CALLBACK (on________t_1_activate),
                    NULL);
  g_signal_connect ((gpointer) _______c_1, "activate",
                    G_CALLBACK (on________c_1_activate),
                    NULL);
  g_signal_connect ((gpointer) _______p_1, "activate",
                    G_CALLBACK (on________p_1_activate),
                    NULL);
  g_signal_connect ((gpointer) _______d_1, "activate",
                    G_CALLBACK (on________d_1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) entry1, "changed",
                    G_CALLBACK (on_entry1_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (topWindow, topWindow, "topWindow");
  GLADE_HOOKUP_OBJECT (topWindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (topWindow, mainMenu, "mainMenu");
  GLADE_HOOKUP_OBJECT (topWindow, menuitem10, "menuitem10");
  GLADE_HOOKUP_OBJECT (topWindow, menu10, "menu10");
  GLADE_HOOKUP_OBJECT (topWindow, _______n_1, "_______n_1");
  GLADE_HOOKUP_OBJECT (topWindow, _______o_1, "_______o_1");
  GLADE_HOOKUP_OBJECT (topWindow, _______s_1, "_______s_1");
  GLADE_HOOKUP_OBJECT (topWindow, __________a_1, "__________a_1");
  GLADE_HOOKUP_OBJECT (topWindow, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (topWindow, _______q_1, "_______q_1");
  GLADE_HOOKUP_OBJECT (topWindow, menuitem11, "menuitem11");
  GLADE_HOOKUP_OBJECT (topWindow, menu11, "menu11");
  GLADE_HOOKUP_OBJECT (topWindow, _______t_1, "_______t_1");
  GLADE_HOOKUP_OBJECT (topWindow, _______c_1, "_______c_1");
  GLADE_HOOKUP_OBJECT (topWindow, _______p_1, "_______p_1");
  GLADE_HOOKUP_OBJECT (topWindow, _______d_1, "_______d_1");
  GLADE_HOOKUP_OBJECT (topWindow, menuitem12, "menuitem12");
  GLADE_HOOKUP_OBJECT (topWindow, menu12, "menu12");
  GLADE_HOOKUP_OBJECT (topWindow, menuitem13, "menuitem13");
  GLADE_HOOKUP_OBJECT (topWindow, menu13, "menu13");
  GLADE_HOOKUP_OBJECT (topWindow, about1, "about1");
  GLADE_HOOKUP_OBJECT (topWindow, toolbar2, "toolbar2");
  GLADE_HOOKUP_OBJECT (topWindow, toolitem6, "toolitem6");
  GLADE_HOOKUP_OBJECT (topWindow, new, "new");
  GLADE_HOOKUP_OBJECT (topWindow, toolitem5, "toolitem5");
  GLADE_HOOKUP_OBJECT (topWindow, close, "close");
  GLADE_HOOKUP_OBJECT (topWindow, toolitem3, "toolitem3");
  GLADE_HOOKUP_OBJECT (topWindow, label3, "label3");
  GLADE_HOOKUP_OBJECT (topWindow, toolitem4, "toolitem4");
  GLADE_HOOKUP_OBJECT (topWindow, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (topWindow, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (topWindow, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (topWindow, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (topWindow, treeview5, "treeview5");
  GLADE_HOOKUP_OBJECT (topWindow, label1, "label1");
  GLADE_HOOKUP_OBJECT (topWindow, scrolledwindow6, "scrolledwindow6");
  GLADE_HOOKUP_OBJECT (topWindow, treeview6, "treeview6");
  GLADE_HOOKUP_OBJECT (topWindow, label2, "label2");
  GLADE_HOOKUP_OBJECT (topWindow, scrolledwindow7, "scrolledwindow7");
  GLADE_HOOKUP_OBJECT (topWindow, textview1, "textview1");

  gtk_window_add_accel_group (GTK_WINDOW (topWindow), accel_group);

  return topWindow;
}

