/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "TellMeTime_constants.h"

namespace jiuzhilan_time {

const TellMeTimeConstants g_TellMeTime_constants;

TellMeTimeConstants::TellMeTimeConstants() {
}

} // namespace

