/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TellMeTime_CONSTANTS_H
#define TellMeTime_CONSTANTS_H

#include "TellMeTime_types.h"

namespace jiuzhilan_time {

class TellMeTimeConstants {
 public:
  TellMeTimeConstants();

};

extern const TellMeTimeConstants g_TellMeTime_constants;

} // namespace

#endif
