//generate2.cpp
#include <iostream>
#include <list>
#include <algorithm>
#include "../print.hpp"
using namespace std;

class IntSequence
{
	public:
		//constructor
		IntSequence(int val): m_basevalue(val) {}

		//fuction call
		int operator() ()
		{
			return m_basevalue++;
		}

	private:
		int m_basevalue;
};

int main()
{
	//define a list container
	list<int> col1;

	//define a fuction object with the init value is 1
	IntSequence seq(1);

	//insert 4 elements generated by seq
	// - pass the function object by reference
	generate_n<back_insert_iterator<list<int> >, int, IntSequence&>(back_inserter(col1),
		       	4, seq);

	//print the col1
	PRINT_ELEMENTS(col1, "col1: ");

	//insert 4 elements beginning with 42
	generate_n(back_inserter(col1), 4, IntSequence(42));

	//print the col1
	PRINT_ELEMENTS(col1, "col1: ");

	//insert 4 elements generated by seq
	// - pass the function object by value
	generate_n(back_inserter(col1), 4, seq);

	//print the col1
	PRINT_ELEMENTS(col1, "col1: ");

	//insert 4 elements generated by seq
	// - pass the function object by value
	generate_n(back_inserter(col1), 4, seq);

	//print the col1
	PRINT_ELEMENTS(col1, "col1: ");
}

